// flow-typed signature: 42cf172dd087ac93bce748ca4b028f61
// flow-typed version: <<STUB>>/ndarray_v^1.0.18/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ndarray'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ndarray' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ndarray/ndarray' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ndarray/ndarray.js' {
  declare module.exports: $Exports<'ndarray/ndarray'>;
}
