// flow-typed signature: 2fd5633ccba6510aa20657d86554ae2d
// flow-typed version: <<STUB>>/object-observer_v^0.2.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-observer/dist/object-observer' {
  declare module.exports: any;
}

declare module 'object-observer/dist/object-observer.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-observer/dist/object-observer.js' {
  declare module.exports: $Exports<'object-observer/dist/object-observer'>;
}
declare module 'object-observer/dist/object-observer.min.js' {
  declare module.exports: $Exports<'object-observer/dist/object-observer.min'>;
}
